enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: /Users/aleksandr/WebProjects/other/showcommits/.yarn/releases/yarn-berry.js
